spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    view:
      suffix: .html
    hidden-method:
      filter:
        enabled: true
  web:
    locale: pl_PL
    locale-resolver: fixed
  profiles:
    active: local

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
